config/routes.rb
MooseHockeyApp::Application.routes.draw do

  resources :players
  resources :seasons
  resources :games

  root to: 'static_pages#home'

  match '/new_player', to: 'players#new'
  match '/new_season', to: 'seasons#new'
  match '/new_game',   to: 'games#new'

  match 'calendar', to: 'static_pages#calendar'
  match 'roster',   to: 'static_pages#roster'

end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id                     :integer          not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  location               :string(255)
#  opponent               :string(255)
#  official               :boolean
#  time                   :time
#  date                   :date
#  scrimmage              :boolean
#  practice               :boolean
#  moose_goals            :integer
#  opponent_goals         :integer
#  moose_assists          :integer
#  opponent_assists       :integer
#  moose_shg              :integer
#  opponent_shg           :integer
#  moose_ppg              :integer
#  opponent_ppg           :integer
#  moose_penalties        :integer
#  opponent_penalties     :integer
#  opponent_shots_on_goal :integer
#  moose_shots_on_goal    :integer
#  season_id              :integer
#

class Game < ActiveRecord::Base
 	attr_accessible :location, :opponent, :time, :date, :official, :scrimmage, 
 					:practice, :opponent_goals, :opponent_assists, :opponent_shg, 
 					:opponent_ppg, :opponent_penalties, :opponent_shots_on_goal, 
 					:moose_goals, :moose_assists, :moose_shg, :moose_ppg, 
 					:moose_penalties, :moose_shots_on_goal

	has_many :memberships
	has_many :players, through: :memberships
	belongs_to :season, inverse_of: :games
	accepts_nested_attributes_for :players

	validates :date, presence: true
	validates :season_id, presence: true
end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id         :integer          not null, primary key
#  player_id  :integer
#  game_id    :integer
#  season_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Membership < ActiveRecord::Base
  
  belongs_to :season
  belongs_to :player
  belongs_to :game
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  number     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  position   :string(255)
#  name       :string(255)
#

class Player < ActiveRecord::Base
	attr_accessible :name, :number, :position, :season_ids, :game_ids

	has_many :memberships
	has_many :seasons, through: :memberships
	has_many :games, through: :memberships
	accepts_nested_attributes_for :seasons

	validates(:name, presence: true)
	validates(:position, presence: true)
	validates(:number, presence: true)
end

app/models/season.rb
# == Schema Information
#
# Table name: seasons
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  season_start   :date
#  season_end     :date
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  current_season :boolean          default(FALSE)
#

class Season < ActiveRecord::Base
  attr_accessible :season_end, :season_start, :name, :player_ids, :current_season
  after_save :falsify_all_others

  has_many :memberships
  has_many :players, through: :memberships
  has_many :games, inverse_of: :season, dependent: :destroy
  accepts_nested_attributes_for :players

  validates(:name, presence: true)

  	private

		def falsify_all_others
  			self.class.where('id != ?', self.id).update_all(current_season: :false)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def new
		@game = Game.new
	end

	def create
		@date = params[:date] ? Date.parse(params[:date]) : Date.today
		@current_season = Season.find_by_current_season(:true)
		@game = @current_season.games.build(params[:game])
		if @game.save
			flash[:success] = "New game created"
			redirect_to @game
		else
			render 'new'
		end
	end

	def show
		@game = Game.find(params[:id])
	end

	def edit
		@game = Game.find(params[:id])
	end

	def update
		@game = Game.find(params[:id])
		if  @game.update_attributes(params[:game])
			flash[:success] = "Game Updated"
			redirect_to game_path(@game)
		else
			render 'edit'
		end
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	def new
		@player = Player.new
	end

	def show
		@player = Player.find(params[:id])
		@seasons = @player.seasons.all
		@games = @player.games.all
	end

	def create
		@player = Player.new(params[:player])
		if @player.save
			flash[:success] = "New player created"
			redirect_to @player
		else
			render 'new'
		end
	end

	def edit
		@player = Player.find(params[:id])
	end

	def update
		@player = Player.find(params[:id])
		if @player.update_attributes(params[:player])
			flash[:success] = "Player Updated"
			redirect_to player_path(@player)
		else
			render 'edit'
		end
	end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
	def new
		@season = Season.new
	end

	def create
		@season = Season.new(params[:season])
		if @season.save
			flash[:success] = "New Season Created"
			redirect_to @season
		else
			render 'new'
		end
	end

	def show
		@season = Season.find(params[:id])
		@players = @season.players.all
		@games = @season.games.all
	end

	def edit
		@season = Season.find(params[:id])
	end

	def update
		@season = Season.find(params[:id])
		if @season.update_attributes(params[:season])
			flash[:success] = "Season Updated"
			redirect_to season_path(@season)
		else
			render 'edit'
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def calendar
  end

  def roster
    @players = Player.all
  end

  def player_pages
  end

  def team_history
  end

  def game_archive
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Moose Hockey"
		if page_title.empty?
			base_title
		else
			"#{base_title} - #{page_title}"
		end
	end
end

app/helpers/games_helper.rb
module GamesHelper

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper

	def current_season=(season)
		@current_season = season
	end

	def current_season
		@current_season = Season.find_by_current_season(:true)
	end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/games/edit.html.erb
<% provide(:title, "Edit #{@game.date}") %>
<h1>Update game on <%= @game.date %></h1>
<div class="row-fluid form-horizontal">
	<div class="span6">
		<%= simple_form_for(@game) do |f| %>
			<%= f.error_notification %>
			<!-- If else needed to simplify tests.
				should return later to test that valid date
				options are being saved to the database. -->
			<% if Rails.env.test? %>
				<%= f.input :date, label: 'Date', as: :text %>
			<% else %>
				<%= f.input :date, as: :datepicker, placeholder: "#{@game.date}"  %>
			<% end %>
			<%= f.input :time,  as: :string, placeholder:"#{@game.time}" %>
			<%= f.input :location, placeholder:"#{@game.location}" %>
			<%= f.input :opponent, placeholder:"#{@game.opponent}" %>
			<%= f.input :official, placeholder:"#{@game.official}", 

									wrapper_html: { class: 'game_class' } %>
			<%= f.input :scrimmage, placeholder:"#{@game.scrimmage}", 

									wrapper_html: { class: 'game_class' } %>

			<%= f.input :practice, placeholder:"#{@game.practice}", 
									wrapper_html: { class: 'game_class' } %>

			<%= f.input :moose_goals, placeholder:"#{@game.moose_goals}" %>
			<%= f.input :opponent_goals, placeholder:"#{@game.opponent_goals}" %>
			<%= f.input :moose_assists, placeholder:"#{@game.moose_assists}" %>
			<%= f.input :opponent_assists, placeholder:"#{@game.opponent_assists}" %>
			<%= f.input :moose_shg, placeholder:"#{@game.moose_shg}" %>
			<%= f.input :opponent_shg, placeholder:"#{@game.opponent_shg}" %>
			<%= f.input :moose_ppg, placeholder:"#{@game.moose_ppg}" %>
			<%= f.input :opponent_ppg, placeholder:"#{@game.opponent_ppg}" %>
			<%= f.input :moose_penalties, placeholder:"#{@game.moose_penalties}" %>
			<%= f.input :opponent_penalties, placeholder:"#{@game.opponent_penalties}" %>
			<%= f.error :base %>
			<%= f.submit "Update Game", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/games/new.html.erb
<%= provide(:title, "New Game") %>
<h1>Create a new game</h1>
<div class="row-fluid form-horizontal">
	<div class="span 6">
		<%= simple_form_for(@game) do |f| %>
			<%= f.error_notification %>
			<!-- If else needed to simplify tests.
				should return later to test that valid date
				options are being saved to the database. -->
			<% if Rails.env.test? %>
				<%= f.input :date, label: 'Date', as: :text %>
			<% else %>
				<%= f.input :date, as: :datepicker %>
			<% end %>
			<%= f.input :time, as: :string %>			
			<%= f.input :location %>			
			<%= f.input :opponent %>
			<%= f.input :official, wrapper_html: { class: 'game_class' } %>
			<%= f.input :scrimmage, wrapper_html: { class: 'game_class' } %>
			<%= f.input :practice, wrapper_html: { class: 'game_class' } %>
			<%= f.input :moose_goals, input_html: { value: '0' } %>
			<%= f.input :opponent_goals, input_html: { value: '0' } %>
			<%= f.input :moose_assists, input_html: { value: '0' } %>
			<%= f.input :opponent_assists, input_html: { value: '0' } %>
			<%= f.input :moose_shg, input_html: { value: '0' } %>
			<%= f.input :opponent_shg, input_html: { value: '0' } %>
			<%= f.input :moose_ppg, input_html: { value: '0' } %>
			<%= f.input :opponent_ppg, input_html: { value: '0' } %>
			<%= f.input :moose_penalties, input_html: { value: '0' } %>
			<%= f.input :opponent_penalties, input_html: { value: '0' } %>
			<%= f.error :base %>
			<%= f.submit "Create Game", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/games/show.html.erb
<% provide(:title, "#{@game.date}") %>
<h1><%= @game.date %></h1>
<h1><%= @game.moose_goals %></h1>
<h1><%= @game.time %></h1>
<h1><%= @game.season.name %></h1>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
			<li>
				<a href="https://twitter.com/ahamoose" class="twitter-follow-button" data-show-count="false" data-dnt="true">Follow @ahamoose</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
				</script>
			</li>
			<li>
				<div id="fb-root"></div>
				<script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) 
				  	return;
				  	js = d.createElement(s); js.id = id;
				  	js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
				  	fjs.parentNode.insertBefore(js, fjs);}
				  	(document, 'script', 'facebook-jssdk'));
				</script>
				<div class="fb-follow" data-href="https://www.facebook.com/AHAMooseHockey" data-width="450" data-show-faces="true"></div>
			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
	<header class="navbar">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to image_tag("PrimaryLogohires.png", size: "250x250", alt: "Moose Hockey"), 
										root_path, id: "logo" %>
				<nav>
					<ul class="nav">
						<li><%= link_to "Calendar", calendar_path %></li>
						<li><%= link_to "Roster", roster_path %></li>
						<li><%= link_to "Team History", '#' %></li>
						<li><%= link_to "Game Archive", '#' %></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<div class="page">
				<% flash.each do |key, value| %>
					<%= content_tag(:div, value, class: "alert alert-#{key}") %>
				<% end %>
				<%= yield %>
				<%= render 'layouts/footer' %>
				<%= debug(params) if Rails.env.development? %>
			</div>
		</div>
	</body>
</html>

app/views/players/_profile_picture.html.erb
<%= image_tag("#{@player.name.downcase}profile.jpeg", 
						size: "250x500", 
						alt: "#{@player.name.titleize}") %>

app/views/players/edit.html.erb
<% provide(:title, "Edit #{@player.name}") %>
<h1>Update <%= "#{@player.name}" %></h1>
<div class="row-fluid form-horizontal">
	<div class="span6">
		<%= simple_form_for @player do |f| %>
			<%= f.error_notification %>
			<%= f.input :name, label: "Name", placeholder: "#{@player.name}" %>
			<%= f.input :number, placeholder: "#{@player.number}" %>
			<%= f.input :position %>
			<%= f.association :seasons, label: "Change Team Membership", as: :check_boxes %>
			<%= f.association :games, label: "Change Games Played", label_method: :date, as: :check_boxes %>
			<%= f.error :base %>
			<%= f.submit "Update Player", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/players/new.html.erb
<% provide(:title, 'New Player') %>
<h1>New Player Creation</h1>
<div class="row-fluid form-horizontal">
	<div class="span 6">
		<%= simple_form_for(@player) do |f| %>
			<%= f.error_notification %>
			<%= f.input :name, label: "Name" %>
			<%= f.input :number %>
			<%= f.input :position %>
			<%= f.error :base %>
			<%= f.submit "Create Player", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/players/show.html.erb
<% provide(:title, "#{@player.name}") %>
<div class="row-fluid">
	<aside class="span5">
		<section>
			<%= render 'profile_picture' %>
			<div class="row-fluid">
				<div class="span8">
					<table class="table table-hover table-condensed">
						<thead>
							<tr>
								<th>Past seasons</th>
							</tr>
						</thead>
						<tbody>
							<% @seasons.each do |season| %>
								<tr> 
									<td><%= link_to "#{season.name}", season %></td>
								</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</section>
	</aside>
	<div class="row-fluid">
		<div class="span7">
			<h1>
				<%= "#{@player.name}" %>
			</h1>
			<p>

			</p>
		</div>
	</div>
</div>

app/views/seasons/edit.html.erb
<% provide(:title, "Edit #{@season.name}") %>
<h1>Update <%= "#{@season.name}" %></h1>
<div class="row-fluid form-horizontal">
	<div class="span 6">
		<%= simple_form_for @season do |f| %>
			<%= f.error_notification %>
			<%= f.input :name, label: "Name", placeholder: "#{@season.name}" %>

			<%= f.input :season_start, label: "Start of season", placeholder: "#{@season.season_start}", as: :datepicker %>

			<%= f.input :season_end, label: "End of season", placeholder: "#{@season.season_end}", as: :datepicker %>

			<%= f.input :current_season, label: "Current Season", placeholder: "#{@season.current_season}" %>

			<%= f.association :players, label: "Select players", as: :check_boxes %>

			<%= f.error :base %>
			<%= f.submit "Update Season", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/seasons/new.html.erb
<% provide(:title, "New Season") %>
<h1>New Season Creation</h1>
<div class="row-fluid form-horizontal">
	<div class="span 6">
		<%= simple_form_for @season do |f| %>
			<%= f.error_notification %>
			<%= f.input :name, label: "Name" %>
			<%= f.input :season_start, label: "Start of season", as: :datepicker %>
			<%= f.input :season_end, label: "End of season", as: :datepicker %>
			<%= f.input :current_season, label: "Current Season" %>
			<%= f.association :players, label: "Select players", as: :check_boxes %>
			<%= f.error :base %>
			<%= f.submit "Create Season", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/seasons/show.html.erb
<% provide(:title, "#{@season.name}") %>
<h1><%= "#{@season.name}" %></h1>
<div class="row-fluid">
	<div class="span8">
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Number</th>
					<th>Name</th>
				</tr>
			</thead>
			<tbody>
				<% @players.each do |player| %>
					<tr> 
						<td><%= player.number %>
						<td><%= link_to "#{player.name}", player %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @player.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@player.errors.count, "error") %>.
		</div>
		<ul>
			<% @player.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/_carousel1.html.erb
<%= image_tag "carousel1.jpeg", size: "600x600" %>

app/views/static_pages/_carousel2.html.erb
<%= image_tag "carousel2.jpeg", size: "600x600" %>

app/views/static_pages/_carousel3.html.erb
<%= image_tag "carousel3.jpeg", size: "600x600" %>

app/views/static_pages/calendar.html.erb
<% provide(:title, 'Calendar') %>
<div class="container">
	<h1>Calendar</h1>
	<div class="calendar">
		<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;height=700&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=ahamoosehockey@gmail.com&amp;ctz=America%2FChicago" style=" border-width:0 " width="790" height="700" frameborder="0" scrolling="no"></iframe>
	</div>
</div>

app/views/static_pages/game_archive.html.erb
<h1>StaticPages#game_archive</h1>
<p>Find me in app/views/static_pages/game_archive.html.erb</p>

app/views/static_pages/home.html.erb
<div class="hero-unit">
	<h1>Moose Hockey</h1>
</div>
	<div id="myCarousel" class="carousel slide">
		<div class="carousel-container">
			<ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
			</ol>
			<!-- Carousel items -->
			<div class="carousel-inner">
				<div class="active item"><%= render "/static_pages/carousel1" %></div>
				<div class="item"><%= render "/static_pages/carousel2" %></div>
				<div class="item"><%= render "/static_pages/carousel3" %></div>
			</div>
		</div>
		<!-- Carousel nav -->
		<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
	</div>

app/views/static_pages/player_pages.html.erb
<h1>StaticPages#player_pages</h1>
<p>Find me in app/views/static_pages/player_pages.html.erb</p>

app/views/static_pages/roster.html.erb
<% provide(:title, "Roster") %>
<h1>Roster</h1>
<div class="row-fluid">
	<div class="span9 offset3">
		<table class="table table-hover table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Position</th>
				</tr>
			</thead>
			<tbody>
				<% @players.each do |player| %>
					<tr> 
						<td><%= player.number %></td>
						<td><%= link_to "#{player.name}", player %></td>
						<td><%= player.position %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/static_pages/team_history.html.erb
<h1>StaticPages#team_history</h1>
<p>Find me in app/views/static_pages/team_history.html.erb</p>